/*
Package openconfig is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was true
in this case).

This package was generated by /go/src/github.com/openconfig/ygot/genutil/names.go
using the following YANG input files:
	- /work/public/release/models/network-instance/openconfig-network-instance.yang
	- /work/public/release/models/mpls/openconfig-mpls.yang
	- /work/public/release/models/optical-transport/openconfig-optical-amplifier.yang
	- /work/public/release/models/optical-transport/openconfig-terminal-device.yang
	- /work/public/release/models/optical-transport/openconfig-transport-line-protection.yang
	- /work/public/release/models/platform/openconfig-platform.yang
	- /work/public/release/models/policy/openconfig-routing-policy.yang
	- /work/public/release/models/lacp/openconfig-lacp.yang
	- /work/public/release/models/system/openconfig-system.yang
	- /work/public/release/models/lldp/openconfig-lldp.yang
	- /work/public/release/models/stp/openconfig-spanning-tree.yang
	- /work/public/release/models/interfaces/openconfig-interfaces.yang
	- /work/public/release/models/interfaces/openconfig-if-ip.yang
	- /work/public/release/models/interfaces/openconfig-if-aggregate.yang
	- /work/public/release/models/interfaces/openconfig-if-ethernet.yang
	- /work/public/release/models/interfaces/openconfig-if-ip-ext.yang
	- /work/public/release/models/local-routing/openconfig-local-routing.yang
	- /work/public/release/models/vlan/openconfig-vlan.yang
	- /work/public/release/models/vlan/openconfig-vlan-types.yang
Imported modules were sourced from:
	- /work/public/...
	- yang/...
*/
package openconfig

import (
	"github.com/openconfig/ygot/ygot"
)

// Acl represents the /openconfig-acl/acl YANG schema element.
type Acl struct {
	ΛMetadata          []ygot.Annotation                      `path:"@" ygotAnnotation:"true"`
	AclSet             map[Acl_AclSet_Key]*Acl_AclSet         `path:"acl-sets/acl-set" module:"openconfig-acl"`
	ΛAclSet            []ygot.Annotation                      `path:"acl-sets/@acl-set" ygotAnnotation:"true"`
	CounterCapability  E_OpenconfigAcl_ACL_COUNTER_CAPABILITY `path:"state/counter-capability" module:"openconfig-acl"`
	ΛCounterCapability []ygot.Annotation                      `path:"state/@counter-capability" ygotAnnotation:"true"`
	Interface          map[string]*Acl_Interface              `path:"interfaces/interface" module:"openconfig-acl"`
	ΛInterface         []ygot.Annotation                      `path:"interfaces/@interface" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl) IsYANGGoStruct() {}

// Acl_AclSet_Key represents the key for list AclSet of element /openconfig-acl/acl.
type Acl_AclSet_Key struct {
	Name string                   `path:"name"`
	Type E_OpenconfigAcl_ACL_TYPE `path:"type"`
}

// Acl_AclSet represents the /openconfig-acl/acl/acl-sets/acl-set YANG schema element.
type Acl_AclSet struct {
	ΛMetadata    []ygot.Annotation               `path:"@" ygotAnnotation:"true"`
	AclEntry     map[uint32]*Acl_AclSet_AclEntry `path:"acl-entries/acl-entry" module:"openconfig-acl"`
	ΛAclEntry    []ygot.Annotation               `path:"acl-entries/@acl-entry" ygotAnnotation:"true"`
	Description  *string                         `path:"config/description" module:"openconfig-acl"`
	ΛDescription []ygot.Annotation               `path:"config/@description" ygotAnnotation:"true"`
	Name         *string                         `path:"config/name|name" module:"openconfig-acl"`
	ΛName        []ygot.Annotation               `path:"config/@name|@name" ygotAnnotation:"true"`
	Type         E_OpenconfigAcl_ACL_TYPE        `path:"config/type|type" module:"openconfig-acl"`
	ΛType        []ygot.Annotation               `path:"config/@type|@type" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_AclSet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_AclSet) IsYANGGoStruct() {}

// Acl_AclSet_AclEntry represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry YANG schema element.
type Acl_AclSet_AclEntry struct {
	ΛMetadata       []ygot.Annotation                   `path:"@" ygotAnnotation:"true"`
	Actions         *Acl_AclSet_AclEntry_Actions        `path:"actions" module:"openconfig-acl"`
	ΛActions        []ygot.Annotation                   `path:"@actions" ygotAnnotation:"true"`
	Description     *string                             `path:"config/description" module:"openconfig-acl"`
	ΛDescription    []ygot.Annotation                   `path:"config/@description" ygotAnnotation:"true"`
	InputInterface  *Acl_AclSet_AclEntry_InputInterface `path:"input-interface" module:"openconfig-acl"`
	ΛInputInterface []ygot.Annotation                   `path:"@input-interface" ygotAnnotation:"true"`
	Ipv4            *Acl_AclSet_AclEntry_Ipv4           `path:"ipv4" module:"openconfig-acl"`
	ΛIpv4           []ygot.Annotation                   `path:"@ipv4" ygotAnnotation:"true"`
	Ipv6            *Acl_AclSet_AclEntry_Ipv6           `path:"ipv6" module:"openconfig-acl"`
	ΛIpv6           []ygot.Annotation                   `path:"@ipv6" ygotAnnotation:"true"`
	L2              *Acl_AclSet_AclEntry_L2             `path:"l2" module:"openconfig-acl"`
	ΛL2             []ygot.Annotation                   `path:"@l2" ygotAnnotation:"true"`
	MatchedOctets   *uint64                             `path:"state/matched-octets" module:"openconfig-acl"`
	ΛMatchedOctets  []ygot.Annotation                   `path:"state/@matched-octets" ygotAnnotation:"true"`
	MatchedPackets  *uint64                             `path:"state/matched-packets" module:"openconfig-acl"`
	ΛMatchedPackets []ygot.Annotation                   `path:"state/@matched-packets" ygotAnnotation:"true"`
	SequenceId      *uint32                             `path:"config/sequence-id|sequence-id" module:"openconfig-acl"`
	ΛSequenceId     []ygot.Annotation                   `path:"config/@sequence-id|@sequence-id" ygotAnnotation:"true"`
	Transport       *Acl_AclSet_AclEntry_Transport      `path:"transport" module:"openconfig-acl"`
	ΛTransport      []ygot.Annotation                   `path:"@transport" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_AclSet_AclEntry implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_AclSet_AclEntry) IsYANGGoStruct() {}

// Acl_AclSet_AclEntry_Actions represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/actions YANG schema element.
type Acl_AclSet_AclEntry_Actions struct {
	ΛMetadata         []ygot.Annotation                 `path:"@" ygotAnnotation:"true"`
	ForwardingAction  E_OpenconfigAcl_FORWARDING_ACTION `path:"config/forwarding-action" module:"openconfig-acl"`
	ΛForwardingAction []ygot.Annotation                 `path:"config/@forwarding-action" ygotAnnotation:"true"`
	LogAction         E_OpenconfigAcl_LOG_ACTION        `path:"config/log-action" module:"openconfig-acl"`
	ΛLogAction        []ygot.Annotation                 `path:"config/@log-action" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_AclSet_AclEntry_Actions implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_AclSet_AclEntry_Actions) IsYANGGoStruct() {}

// Acl_AclSet_AclEntry_InputInterface represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/input-interface YANG schema element.
type Acl_AclSet_AclEntry_InputInterface struct {
	ΛMetadata     []ygot.Annotation                                `path:"@" ygotAnnotation:"true"`
	InterfaceRef  *Acl_AclSet_AclEntry_InputInterface_InterfaceRef `path:"interface-ref" module:"openconfig-acl"`
	ΛInterfaceRef []ygot.Annotation                                `path:"@interface-ref" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_AclSet_AclEntry_InputInterface implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_AclSet_AclEntry_InputInterface) IsYANGGoStruct() {}

// Acl_AclSet_AclEntry_InputInterface_InterfaceRef represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/input-interface/interface-ref YANG schema element.
type Acl_AclSet_AclEntry_InputInterface_InterfaceRef struct {
	ΛMetadata     []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Interface     *string           `path:"config/interface" module:"openconfig-acl"`
	ΛInterface    []ygot.Annotation `path:"config/@interface" ygotAnnotation:"true"`
	Subinterface  *uint32           `path:"config/subinterface" module:"openconfig-acl"`
	ΛSubinterface []ygot.Annotation `path:"config/@subinterface" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_AclSet_AclEntry_InputInterface_InterfaceRef implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_AclSet_AclEntry_InputInterface_InterfaceRef) IsYANGGoStruct() {}

// Acl_AclSet_AclEntry_Ipv4 represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4 YANG schema element.
type Acl_AclSet_AclEntry_Ipv4 struct {
	ΛMetadata           []ygot.Annotation                       `path:"@" ygotAnnotation:"true"`
	DestinationAddress  *string                                 `path:"config/destination-address" module:"openconfig-acl"`
	ΛDestinationAddress []ygot.Annotation                       `path:"config/@destination-address" ygotAnnotation:"true"`
	Dscp                *uint8                                  `path:"config/dscp" module:"openconfig-acl"`
	ΛDscp               []ygot.Annotation                       `path:"config/@dscp" ygotAnnotation:"true"`
	HopLimit            *uint8                                  `path:"config/hop-limit" module:"openconfig-acl"`
	ΛHopLimit           []ygot.Annotation                       `path:"config/@hop-limit" ygotAnnotation:"true"`
	Protocol            Acl_AclSet_AclEntry_Ipv4_Protocol_Union `path:"config/protocol" module:"openconfig-acl"`
	ΛProtocol           []ygot.Annotation                       `path:"config/@protocol" ygotAnnotation:"true"`
	SourceAddress       *string                                 `path:"config/source-address" module:"openconfig-acl"`
	ΛSourceAddress      []ygot.Annotation                       `path:"config/@source-address" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_AclSet_AclEntry_Ipv4 implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_AclSet_AclEntry_Ipv4) IsYANGGoStruct() {}

// Acl_AclSet_AclEntry_Ipv6 represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv6 YANG schema element.
type Acl_AclSet_AclEntry_Ipv6 struct {
	ΛMetadata             []ygot.Annotation                       `path:"@" ygotAnnotation:"true"`
	DestinationAddress    *string                                 `path:"config/destination-address" module:"openconfig-acl"`
	ΛDestinationAddress   []ygot.Annotation                       `path:"config/@destination-address" ygotAnnotation:"true"`
	DestinationFlowLabel  *uint32                                 `path:"config/destination-flow-label" module:"openconfig-acl"`
	ΛDestinationFlowLabel []ygot.Annotation                       `path:"config/@destination-flow-label" ygotAnnotation:"true"`
	Dscp                  *uint8                                  `path:"config/dscp" module:"openconfig-acl"`
	ΛDscp                 []ygot.Annotation                       `path:"config/@dscp" ygotAnnotation:"true"`
	HopLimit              *uint8                                  `path:"config/hop-limit" module:"openconfig-acl"`
	ΛHopLimit             []ygot.Annotation                       `path:"config/@hop-limit" ygotAnnotation:"true"`
	Protocol              Acl_AclSet_AclEntry_Ipv6_Protocol_Union `path:"config/protocol" module:"openconfig-acl"`
	ΛProtocol             []ygot.Annotation                       `path:"config/@protocol" ygotAnnotation:"true"`
	SourceAddress         *string                                 `path:"config/source-address" module:"openconfig-acl"`
	ΛSourceAddress        []ygot.Annotation                       `path:"config/@source-address" ygotAnnotation:"true"`
	SourceFlowLabel       *uint32                                 `path:"config/source-flow-label" module:"openconfig-acl"`
	ΛSourceFlowLabel      []ygot.Annotation                       `path:"config/@source-flow-label" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_AclSet_AclEntry_Ipv6 implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_AclSet_AclEntry_Ipv6) IsYANGGoStruct() {}

// Acl_AclSet_AclEntry_L2 represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/l2 YANG schema element.
type Acl_AclSet_AclEntry_L2 struct {
	ΛMetadata           []ygot.Annotation                      `path:"@" ygotAnnotation:"true"`
	DestinationMac      *string                                `path:"config/destination-mac" module:"openconfig-acl"`
	ΛDestinationMac     []ygot.Annotation                      `path:"config/@destination-mac" ygotAnnotation:"true"`
	DestinationMacMask  *string                                `path:"config/destination-mac-mask" module:"openconfig-acl"`
	ΛDestinationMacMask []ygot.Annotation                      `path:"config/@destination-mac-mask" ygotAnnotation:"true"`
	Ethertype           Acl_AclSet_AclEntry_L2_Ethertype_Union `path:"config/ethertype" module:"openconfig-acl"`
	ΛEthertype          []ygot.Annotation                      `path:"config/@ethertype" ygotAnnotation:"true"`
	SourceMac           *string                                `path:"config/source-mac" module:"openconfig-acl"`
	ΛSourceMac          []ygot.Annotation                      `path:"config/@source-mac" ygotAnnotation:"true"`
	SourceMacMask       *string                                `path:"config/source-mac-mask" module:"openconfig-acl"`
	ΛSourceMacMask      []ygot.Annotation                      `path:"config/@source-mac-mask" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_AclSet_AclEntry_L2 implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_AclSet_AclEntry_L2) IsYANGGoStruct() {}

// Acl_AclSet_AclEntry_Transport represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport YANG schema element.
type Acl_AclSet_AclEntry_Transport struct {
	ΛMetadata        []ygot.Annotation                                   `path:"@" ygotAnnotation:"true"`
	DestinationPort  Acl_AclSet_AclEntry_Transport_DestinationPort_Union `path:"config/destination-port" module:"openconfig-acl"`
	ΛDestinationPort []ygot.Annotation                                   `path:"config/@destination-port" ygotAnnotation:"true"`
	SourcePort       Acl_AclSet_AclEntry_Transport_SourcePort_Union      `path:"config/source-port" module:"openconfig-acl"`
	ΛSourcePort      []ygot.Annotation                                   `path:"config/@source-port" ygotAnnotation:"true"`
	TcpFlags         []E_OpenconfigPacketMatchTypes_TCP_FLAGS            `path:"config/tcp-flags" module:"openconfig-acl"`
	ΛTcpFlags        []ygot.Annotation                                   `path:"config/@tcp-flags" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_AclSet_AclEntry_Transport implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_AclSet_AclEntry_Transport) IsYANGGoStruct() {}

// Acl_Interface represents the /openconfig-acl/acl/interfaces/interface YANG schema element.
type Acl_Interface struct {
	ΛMetadata      []ygot.Annotation                                                `path:"@" ygotAnnotation:"true"`
	EgressAclSet   map[Acl_Interface_EgressAclSet_Key]*Acl_Interface_EgressAclSet   `path:"egress-acl-sets/egress-acl-set" module:"openconfig-acl"`
	ΛEgressAclSet  []ygot.Annotation                                                `path:"egress-acl-sets/@egress-acl-set" ygotAnnotation:"true"`
	Id             *string                                                          `path:"config/id|id" module:"openconfig-acl"`
	ΛId            []ygot.Annotation                                                `path:"config/@id|@id" ygotAnnotation:"true"`
	IngressAclSet  map[Acl_Interface_IngressAclSet_Key]*Acl_Interface_IngressAclSet `path:"ingress-acl-sets/ingress-acl-set" module:"openconfig-acl"`
	ΛIngressAclSet []ygot.Annotation                                                `path:"ingress-acl-sets/@ingress-acl-set" ygotAnnotation:"true"`
	InterfaceRef   *Acl_Interface_InterfaceRef                                      `path:"interface-ref" module:"openconfig-acl"`
	ΛInterfaceRef  []ygot.Annotation                                                `path:"@interface-ref" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_Interface implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_Interface) IsYANGGoStruct() {}

// Acl_Interface_EgressAclSet_Key represents the key for list EgressAclSet of element /openconfig-acl/acl/interfaces/interface.
type Acl_Interface_EgressAclSet_Key struct {
	SetName string                   `path:"set-name"`
	Type    E_OpenconfigAcl_ACL_TYPE `path:"type"`
}

// Acl_Interface_IngressAclSet_Key represents the key for list IngressAclSet of element /openconfig-acl/acl/interfaces/interface.
type Acl_Interface_IngressAclSet_Key struct {
	SetName string                   `path:"set-name"`
	Type    E_OpenconfigAcl_ACL_TYPE `path:"type"`
}

// Acl_Interface_EgressAclSet represents the /openconfig-acl/acl/interfaces/interface/egress-acl-sets/egress-acl-set YANG schema element.
type Acl_Interface_EgressAclSet struct {
	ΛMetadata []ygot.Annotation                               `path:"@" ygotAnnotation:"true"`
	AclEntry  map[uint32]*Acl_Interface_EgressAclSet_AclEntry `path:"acl-entries/acl-entry" module:"openconfig-acl"`
	ΛAclEntry []ygot.Annotation                               `path:"acl-entries/@acl-entry" ygotAnnotation:"true"`
	SetName   *string                                         `path:"config/set-name|set-name" module:"openconfig-acl"`
	ΛSetName  []ygot.Annotation                               `path:"config/@set-name|@set-name" ygotAnnotation:"true"`
	Type      E_OpenconfigAcl_ACL_TYPE                        `path:"config/type|type" module:"openconfig-acl"`
	ΛType     []ygot.Annotation                               `path:"config/@type|@type" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_Interface_EgressAclSet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_Interface_EgressAclSet) IsYANGGoStruct() {}

// Acl_Interface_EgressAclSet_AclEntry represents the /openconfig-acl/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_EgressAclSet_AclEntry struct {
	ΛMetadata       []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	MatchedOctets   *uint64           `path:"state/matched-octets" module:"openconfig-acl"`
	ΛMatchedOctets  []ygot.Annotation `path:"state/@matched-octets" ygotAnnotation:"true"`
	MatchedPackets  *uint64           `path:"state/matched-packets" module:"openconfig-acl"`
	ΛMatchedPackets []ygot.Annotation `path:"state/@matched-packets" ygotAnnotation:"true"`
	SequenceId      *uint32           `path:"state/sequence-id|sequence-id" module:"openconfig-acl"`
	ΛSequenceId     []ygot.Annotation `path:"state/@sequence-id|@sequence-id" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_Interface_EgressAclSet_AclEntry implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_Interface_EgressAclSet_AclEntry) IsYANGGoStruct() {}

// Acl_Interface_IngressAclSet represents the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set YANG schema element.
type Acl_Interface_IngressAclSet struct {
	ΛMetadata []ygot.Annotation                                `path:"@" ygotAnnotation:"true"`
	AclEntry  map[uint32]*Acl_Interface_IngressAclSet_AclEntry `path:"acl-entries/acl-entry" module:"openconfig-acl"`
	ΛAclEntry []ygot.Annotation                                `path:"acl-entries/@acl-entry" ygotAnnotation:"true"`
	SetName   *string                                          `path:"config/set-name|set-name" module:"openconfig-acl"`
	ΛSetName  []ygot.Annotation                                `path:"config/@set-name|@set-name" ygotAnnotation:"true"`
	Type      E_OpenconfigAcl_ACL_TYPE                         `path:"config/type|type" module:"openconfig-acl"`
	ΛType     []ygot.Annotation                                `path:"config/@type|@type" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_Interface_IngressAclSet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_Interface_IngressAclSet) IsYANGGoStruct() {}

// Acl_Interface_IngressAclSet_AclEntry represents the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_IngressAclSet_AclEntry struct {
	ΛMetadata       []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	MatchedOctets   *uint64           `path:"state/matched-octets" module:"openconfig-acl"`
	ΛMatchedOctets  []ygot.Annotation `path:"state/@matched-octets" ygotAnnotation:"true"`
	MatchedPackets  *uint64           `path:"state/matched-packets" module:"openconfig-acl"`
	ΛMatchedPackets []ygot.Annotation `path:"state/@matched-packets" ygotAnnotation:"true"`
	SequenceId      *uint32           `path:"state/sequence-id|sequence-id" module:"openconfig-acl"`
	ΛSequenceId     []ygot.Annotation `path:"state/@sequence-id|@sequence-id" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_Interface_IngressAclSet_AclEntry implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_Interface_IngressAclSet_AclEntry) IsYANGGoStruct() {}

// Acl_Interface_InterfaceRef represents the /openconfig-acl/acl/interfaces/interface/interface-ref YANG schema element.
type Acl_Interface_InterfaceRef struct {
	ΛMetadata     []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Interface     *string           `path:"config/interface" module:"openconfig-acl"`
	ΛInterface    []ygot.Annotation `path:"config/@interface" ygotAnnotation:"true"`
	Subinterface  *uint32           `path:"config/subinterface" module:"openconfig-acl"`
	ΛSubinterface []ygot.Annotation `path:"config/@subinterface" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Acl_Interface_InterfaceRef implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Acl_Interface_InterfaceRef) IsYANGGoStruct() {}

// Aps represents the /openconfig-transport-line-protection/aps YANG schema element.
type Aps struct {
	ΛMetadata  []ygot.Annotation         `path:"@" ygotAnnotation:"true"`
	ApsModule  map[string]*Aps_ApsModule `path:"aps-modules/aps-module" module:"openconfig-transport-line-protection"`
	ΛApsModule []ygot.Annotation         `path:"aps-modules/@aps-module" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps) IsYANGGoStruct() {}

// Aps_ApsModule represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module YANG schema element.
type Aps_ApsModule struct {
	ΛMetadata                      []ygot.Annotation                                         `path:"@" ygotAnnotation:"true"`
	ActivePath                     E_OpenconfigTransportLineProtection_APS_PATHS             `path:"state/active-path" module:"openconfig-transport-line-protection"`
	ΛActivePath                    []ygot.Annotation                                         `path:"state/@active-path" ygotAnnotation:"true"`
	ForceToPort                    E_OpenconfigTransportLineProtection_ApsModule_ForceToPort `path:"config/force-to-port" module:"openconfig-transport-line-protection"`
	ΛForceToPort                   []ygot.Annotation                                         `path:"config/@force-to-port" ygotAnnotation:"true"`
	HoldOffTime                    *uint32                                                   `path:"config/hold-off-time" module:"openconfig-transport-line-protection"`
	ΛHoldOffTime                   []ygot.Annotation                                         `path:"config/@hold-off-time" ygotAnnotation:"true"`
	Name                           *string                                                   `path:"config/name|name" module:"openconfig-transport-line-protection"`
	ΛName                          []ygot.Annotation                                         `path:"config/@name|@name" ygotAnnotation:"true"`
	Ports                          *Aps_ApsModule_Ports                                      `path:"ports" module:"openconfig-transport-line-protection"`
	ΛPorts                         []ygot.Annotation                                         `path:"@ports" ygotAnnotation:"true"`
	PrimarySwitchHysteresis        *float64                                                  `path:"config/primary-switch-hysteresis" module:"openconfig-transport-line-protection"`
	ΛPrimarySwitchHysteresis       []ygot.Annotation                                         `path:"config/@primary-switch-hysteresis" ygotAnnotation:"true"`
	PrimarySwitchThreshold         *float64                                                  `path:"config/primary-switch-threshold" module:"openconfig-transport-line-protection"`
	ΛPrimarySwitchThreshold        []ygot.Annotation                                         `path:"config/@primary-switch-threshold" ygotAnnotation:"true"`
	RelativeSwitchThreshold        *float64                                                  `path:"config/relative-switch-threshold" module:"openconfig-transport-line-protection"`
	ΛRelativeSwitchThreshold       []ygot.Annotation                                         `path:"config/@relative-switch-threshold" ygotAnnotation:"true"`
	RelativeSwitchThresholdOffset  *float64                                                  `path:"config/relative-switch-threshold-offset" module:"openconfig-transport-line-protection"`
	ΛRelativeSwitchThresholdOffset []ygot.Annotation                                         `path:"config/@relative-switch-threshold-offset" ygotAnnotation:"true"`
	Revertive                      *bool                                                     `path:"config/revertive" module:"openconfig-transport-line-protection"`
	ΛRevertive                     []ygot.Annotation                                         `path:"config/@revertive" ygotAnnotation:"true"`
	SecondarySwitchThreshold       *float64                                                  `path:"config/secondary-switch-threshold" module:"openconfig-transport-line-protection"`
	ΛSecondarySwitchThreshold      []ygot.Annotation                                         `path:"config/@secondary-switch-threshold" ygotAnnotation:"true"`
	WaitToRestoreTime              *uint32                                                   `path:"config/wait-to-restore-time" module:"openconfig-transport-line-protection"`
	ΛWaitToRestoreTime             []ygot.Annotation                                         `path:"config/@wait-to-restore-time" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule) IsYANGGoStruct() {}

// Aps_ApsModule_Ports represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports YANG schema element.
type Aps_ApsModule_Ports struct {
	ΛMetadata         []ygot.Annotation                     `path:"@" ygotAnnotation:"true"`
	CommonIn          *Aps_ApsModule_Ports_CommonIn         `path:"common-in" module:"openconfig-transport-line-protection"`
	ΛCommonIn         []ygot.Annotation                     `path:"@common-in" ygotAnnotation:"true"`
	CommonOutput      *Aps_ApsModule_Ports_CommonOutput     `path:"common-output" module:"openconfig-transport-line-protection"`
	ΛCommonOutput     []ygot.Annotation                     `path:"@common-output" ygotAnnotation:"true"`
	LinePrimaryIn     *Aps_ApsModule_Ports_LinePrimaryIn    `path:"line-primary-in" module:"openconfig-transport-line-protection"`
	ΛLinePrimaryIn    []ygot.Annotation                     `path:"@line-primary-in" ygotAnnotation:"true"`
	LinePrimaryOut    *Aps_ApsModule_Ports_LinePrimaryOut   `path:"line-primary-out" module:"openconfig-transport-line-protection"`
	ΛLinePrimaryOut   []ygot.Annotation                     `path:"@line-primary-out" ygotAnnotation:"true"`
	LineSecondaryIn   *Aps_ApsModule_Ports_LineSecondaryIn  `path:"line-secondary-in" module:"openconfig-transport-line-protection"`
	ΛLineSecondaryIn  []ygot.Annotation                     `path:"@line-secondary-in" ygotAnnotation:"true"`
	LineSecondaryOut  *Aps_ApsModule_Ports_LineSecondaryOut `path:"line-secondary-out" module:"openconfig-transport-line-protection"`
	ΛLineSecondaryOut []ygot.Annotation                     `path:"@line-secondary-out" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_CommonIn represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/common-in YANG schema element.
type Aps_ApsModule_Ports_CommonIn struct {
	ΛMetadata          []ygot.Annotation                          `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                   `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                          `path:"state/@attenuation" ygotAnnotation:"true"`
	Enabled            *bool                                      `path:"config/enabled" module:"openconfig-transport-line-protection"`
	ΛEnabled           []ygot.Annotation                          `path:"config/@enabled" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_CommonIn_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                          `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                   `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                          `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_CommonIn implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_CommonIn) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_CommonIn_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/common-in/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_CommonIn_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	MaxTime   *uint64           `path:"max-time" module:"openconfig-transport-line-protection"`
	ΛMaxTime  []ygot.Annotation `path:"@max-time" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
	MinTime   *uint64           `path:"min-time" module:"openconfig-transport-line-protection"`
	ΛMinTime  []ygot.Annotation `path:"@min-time" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_CommonIn_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_CommonIn_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_CommonOutput represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/common-output YANG schema element.
type Aps_ApsModule_Ports_CommonOutput struct {
	ΛMetadata          []ygot.Annotation                              `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                       `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                              `path:"state/@attenuation" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_CommonOutput_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                              `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                       `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                              `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_CommonOutput implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_CommonOutput) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_CommonOutput_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/common-output/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_CommonOutput_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	MaxTime   *uint64           `path:"max-time" module:"openconfig-transport-line-protection"`
	ΛMaxTime  []ygot.Annotation `path:"@max-time" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
	MinTime   *uint64           `path:"min-time" module:"openconfig-transport-line-protection"`
	ΛMinTime  []ygot.Annotation `path:"@min-time" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_CommonOutput_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_CommonOutput_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LinePrimaryIn represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-primary-in YANG schema element.
type Aps_ApsModule_Ports_LinePrimaryIn struct {
	ΛMetadata          []ygot.Annotation                               `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                        `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                               `path:"state/@attenuation" ygotAnnotation:"true"`
	Enabled            *bool                                           `path:"config/enabled" module:"openconfig-transport-line-protection"`
	ΛEnabled           []ygot.Annotation                               `path:"config/@enabled" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                               `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                        `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                               `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LinePrimaryIn implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LinePrimaryIn) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-primary-in/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	MaxTime   *uint64           `path:"max-time" module:"openconfig-transport-line-protection"`
	ΛMaxTime  []ygot.Annotation `path:"@max-time" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
	MinTime   *uint64           `path:"min-time" module:"openconfig-transport-line-protection"`
	ΛMinTime  []ygot.Annotation `path:"@min-time" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LinePrimaryOut represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-primary-out YANG schema element.
type Aps_ApsModule_Ports_LinePrimaryOut struct {
	ΛMetadata          []ygot.Annotation                                `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                         `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                                `path:"state/@attenuation" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                                `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                         `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                                `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LinePrimaryOut implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LinePrimaryOut) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-primary-out/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	MaxTime   *uint64           `path:"max-time" module:"openconfig-transport-line-protection"`
	ΛMaxTime  []ygot.Annotation `path:"@max-time" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
	MinTime   *uint64           `path:"min-time" module:"openconfig-transport-line-protection"`
	ΛMinTime  []ygot.Annotation `path:"@min-time" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LineSecondaryIn represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-secondary-in YANG schema element.
type Aps_ApsModule_Ports_LineSecondaryIn struct {
	ΛMetadata          []ygot.Annotation                                 `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                          `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                                 `path:"state/@attenuation" ygotAnnotation:"true"`
	Enabled            *bool                                             `path:"config/enabled" module:"openconfig-transport-line-protection"`
	ΛEnabled           []ygot.Annotation                                 `path:"config/@enabled" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                                 `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                          `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                                 `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LineSecondaryIn implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LineSecondaryIn) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-secondary-in/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	MaxTime   *uint64           `path:"max-time" module:"openconfig-transport-line-protection"`
	ΛMaxTime  []ygot.Annotation `path:"@max-time" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
	MinTime   *uint64           `path:"min-time" module:"openconfig-transport-line-protection"`
	ΛMinTime  []ygot.Annotation `path:"@min-time" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LineSecondaryOut represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-secondary-out YANG schema element.
type Aps_ApsModule_Ports_LineSecondaryOut struct {
	ΛMetadata          []ygot.Annotation                                  `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                           `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                                  `path:"state/@attenuation" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                                  `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                           `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                                  `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LineSecondaryOut implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LineSecondaryOut) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-secondary-out/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	MaxTime   *uint64           `path:"max-time" module:"openconfig-transport-line-protection"`
	ΛMaxTime  []ygot.Annotation `path:"@max-time" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
	MinTime   *uint64           `path:"min-time" module:"openconfig-transport-line-protection"`
	ΛMinTime  []ygot.Annotation `path:"@min-time" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower) IsYANGGoStruct() {}
