on:
  push:
    branches:
      - '*'

name: Build and release
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@master

    - name: Validate
      run: make test
